idf_component_register(SRCS 10vSpindle.cpp BESCSpindle.cpp DacSpindle.cpp HBridgeSpindle.cpp LaserSpindle.cpp NullSpindle.cpp OnOffSpindle.cpp PlasmaSpindle.cpp
                            PWMSpindle.cpp RelaySpindle.cpp Spindle.cpp VFDSpindle.cpp
                            VFD/DanfossVLT2800Protocol.cpp VFD/GenericProtocol.cpp VFD/H100Protocol.cpp VFD/H2AProtocol.cpp VFD/HuanyangProtocol.cpp
                            VFD/NowForeverProtocol.cpp VFD/SiemensV20Protocol.cpp VFD/VFDProtocol.cpp VFD/YL620Protocol.cpp
                       INCLUDE_DIRS "." "../..")
