idf_component_register(SRC_DIRS "."
                       SRCS Authentication.cpp Mdns.cpp NotificationsService.cpp OTA.cpp TelnetClient.cpp TelnetServer.cpp WebClient.cpp 
                            WebCommands.cpp WebServer.cpp WifiConfig.cpp WSChannel.cpp
                       INCLUDE_DIRS "." "../..")
