idf_component_register(SRC_DIRS "."
                       SRCS ChannelPinDetail.cpp DebugPinDetail.cpp ErrorPinDetail.cpp GPIOPinDetail.cpp I2SOPinDetail.cpp PinAttributes.cpp PinCapabilities.cpp 
                            PinDetail.cpp PinOptionsParser.cpp VoidPinDetail.cpp
                       INCLUDE_DIRS "." "../.." "../../include/")
